### ISSUE TITLE
Widget gets closed automatically after completing a transaction on all the chains

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#86]
Steps to reproduce:
1.Open demo app
2.Connect the sign in to safle id
3.Then Try to complete a transaction from any change (try both type 1 and type 2 transaction)
4.Check the widget once the transaction success popup is visible 

Actual result:
Widget gets closed automatically after completing a transaction on all the chains

https://github.com/getsafle/safle-keyless-js/assets/149378074/83197e7a-60fc-4d50-983b-af6fb93108e9

Expected result:
Widget should not be closed once after completing a transaction
user must be allowed to click on success buttons and navigate to appropriate screens

Note : widget should not be closed on clicking blockchain explorer button
widget should be navigating the user to dashboard on clicking go to dashboard button

Widget should be closed only if user clicks on x button

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/1d891955-41c0-48f4-b5d6-b2419328afc2

Still able to replicate the issue 
Widget is autoclosed at  the time of tranasaction success popup

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/bc7989d8-42b6-4818-a4dc-377d15a5c459

Issue is still replicable

**Comment by surajsingla333** [comment]
https://drive.google.com/file/d/1014kWACLngO0yOndq7_ko6CPOyTCFVmR/view?usp=sharing
Fixed

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/80c191b1-8b23-4532-9732-c7329fece574

issue is still replicable @surajsingla333

**Comment by mohancool94** [comment]
Uploading 12.12.2023_10.24.26_REC.mp4…

Fixed
