### ISSUE TITLE
Chain selection dropdown Scroll bar needs to be similar like wallet dropdown scroller and should be matching with figma

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#99]
Steps to reproduce:
1.Open keyless demo app
2.Connect with any safle id user
3.Then check the scroller on chain selection dropdown

Actual result:
Scroller is not matching the figma design and making the application unattractive

![Image](https://github.com/getsafle/safle-keyless-js/assets/149378074/34193bc7-0050-4a26-aea5-52305eccf34a)

Expected result:

![Image](https://github.com/getsafle/safle-keyless-js/assets/149378074/15936f67-3bd4-4a3b-b1e6-2eeb5954d83d)

Need to make the scroller similar to wallet drop down scroller 
it should be matching the design on figma

**Comment by surajsingla333** [comment]
Fixed,
https://drive.google.com/file/d/187aE4r9a6IEn-cvhLDMN1Nf4y8TktvK6/view?usp=sharing

**Comment by mohancool94** [comment]
![image](https://github.com/getsafle/safle-keyless-js/assets/149378074/ce458387-cf08-4833-93c0-75f30d51a39a)


Issue is still there

**Comment by mohancool94** [comment]
![Screenshot_1782](https://github.com/getsafle/safle-keyless-js/assets/149378074/c77a4d6e-32e1-43f7-9ed5-ad1fd59013c2)
Fixed now
